# Generated by Django 3.2.7 on 2021-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bio', models.TextField(max_length=500)),
                ('size', models.PositiveIntegerField()),
                ('abv', models.FloatField()),
                ('image', models.CharField(max_length=500, unique=True)),
                ('price', models.FloatField()),
                ('origin', models.CharField(max_length=200)),
                ('botanicals', models.CharField(max_length=200)),
                ('tasting_notes', models.TextField(max_length=500)),
                ('perfect_gt', models.CharField(max_length=200)),
            ],
        ),
    ]
