# Generated by Django 3.2.7 on 2021-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0003_gin_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gin',
            name='flavour',
            field=models.CharField(max_length=50),
        ),
    ]
