# Generated by Django 3.2.7 on 2021-09-09 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gins', '0004_alter_gin_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='gin',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_gins', to=settings.AUTH_USER_MODEL),
        ),
    ]
