# Generated by Django 3.2.7 on 2021-09-10 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0005_gin_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rated',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
