# Generated by Django 3.2.7 on 2021-09-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0006_comment_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='gin',
            name='is_premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
