# Generated by Django 3.2.7 on 2021-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0005_gin_liked_by'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_gins', to='gins.Gin'),
        ),
    ]
